### 创建服务端
POST http://localhost:3000/ws/add HTTP/1.1
Content-Type : application/json

{}

### 服务端推送消息到指定client
POST http://localhost:3000/ws/push HTTP/1.1
Content-Type : application/json

{
  "id":"clientId",
  "msg":"message from server" 
}

### 得到服务端的nsp结构
POST http://localhost:3000/ws/getNspLevel HTTP/1.1
Content-Type : application/json

{
}

### 服务端广播消息

### 客户端推送消息到服务端

### 客户端推送消息到其他客户端

### 发现新的盘头通知到客户端