### 创建服务端
POST http://localhost:3000/ws/add HTTP/1.1
Content-Type : application/json

{}

### 服务端推送消息到指定client
POST http://localhost:3000/ws/push HTTP/1.1
Content-Type : application/json

{
  "id":"clientId",
  "msg":"message from server" 
}

### 得到服务端的nsp结构
POST http://localhost:3000/ws/getNspLevel HTTP/1.1
Content-Type : application/json

{}